[package]
name = "pioc-cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "pioc"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
pioc = { path = "../pioc" }
